### ISSUE TITLE
Can you release a 0.1.0?

### ISSUE THREAD

**Issue by Natim** [dgilman/gspread_asyncio#1]
Would you be interested in a pull-request to help you release this as a lib? I would be interested in using the Asyncio wrapper.

**Comment by dgilman** [comment]
Rémy, I would welcome a pull request. As you can see from the tons of comments at the top of the file I have the code in shape for my internal usage but have not yet had the time to package, document it or make a few API changes. I can only work on those in the next month or two when I will have free time so any code changes you are willing to make now will be welcome.

There are also a few minor bugfixes I have in my internal copy that I can push to this repo later.

Do you have a preference on license? I was going to do BSD but am interested in your input.

I will be away from my development PC from Sept 1-15 so I won't be able to make any changes during that time.

**Comment by Natim** [comment]
BSD seems good to me, I will see what I can do ;)

**Comment by dgilman** [comment]
There is a version 0.1.8 uploaded to PyPI so I will close this issue. No promises on if it works, testing is getting added for version 1.0 😉.
