### ISSUE TITLE
worksheet.Cell(row,col) does not have "value" as an attribute

### ISSUE THREAD

**Issue by Swimmerhair** [dgilman/gspread_asyncio#17]
I have this line: 

   ` msg = await ws.cell(row,col).value`

But I get an error stating that: 

`AttributeError: 'coroutine' object has no attribute 'value'`

**Comment by dgilman** [comment]
I believe the issue here is with operator precedence. First, `ws.cell()` is called, returning a coroutine. Next, the dot operator is called and that throws your error.

You might be able to fix this with
    (await ws.cell(row, col)).value
Or personally, I'd break it into two lines:
    c = await ws.cell(row, col)
    msg = c.val

**Comment by Swimmerhair** [comment]
That seems to fix it, thank you!
