### ISSUE TITLE
AGC.del_spreadsheet only updates 1 of 2 caches

### ISSUE THREAD

**Issue by Skaft** [dgilman/gspread_asyncio#28]
AsyncioGspreadClient.del_spreadsheet doesn't remove the sheet from the _ss_cache_title cache. So if you delete and recreate a sheet with the same name, then the AGC.open() function grabs the cached, deleted sheet and things go bad.

**Comment by dgilman** [comment]
Fixed in gspread_asyncio 1.2.0
