### ISSUE TITLE
Add Formatting Support

### ISSUE THREAD

**Issue by nzsmith1** [dgilman/gspread_asyncio#32]
Would it be possible to roll in async formatting support based on this project? https://pypi.org/project/gspread-formatting/

**Comment by dgilman** [comment]
I'd accept a patch doing this but I won't implement it. I don't have a need and it seems like a pretty tricky thing to pull off. They're tightly coupled to the gspread objects and it would probably be easiest to just start from scratch and re-implement their API in gspread_asyncio.

**Comment by dgilman** [comment]
The upcoming version 1.6 will include the format() methods now supported in gspread!
