### ISSUE TITLE
Feature request - async duplicate worksheet

### ISSUE THREAD

**Issue by Prozer1** [dgilman/gspread_asyncio#38]
Hello,

In the regular Gspread there is a method called duplicate_sheet. Will it be possible to have this one available for asyncioGspead ?

Code link to gspread : https://github.com/burnash/gspread/blob/a52db7006f7906eca42fff058deb254526c4cb08/gspread/models.py#L364

Thanks a lot !

**Comment by dgilman** [comment]
This will be added in the upcoming 1.6 release!
