### ISSUE TITLE
Worksheet's `update()` coroutine method's `raw` parameter is ignored

### ISSUE THREAD

**Issue by alexdelorenzo** [dgilman/gspread_asyncio#40]
Using `gspread_asyncio.AsyncGspreadWorksheet`'s `update()` method to add, say, formulas to a cell, isn't possible. Formulas will be sent as raw content, even if you pass the `raw=False` parameter:
```python3
import gspread_asyncio

FORMULA: str = '=SUM(A1:C1)'
LOCATION: str = 'A2'

sheet: gspread_asyncio.AsyncGspreadWorksheet = ...
await sheet.update(LOCATION, FORMULA, raw=False)
```
Cell `A2` will be updated with the text `=SUM(A1:C1)`, and *not* the formula it should be parsed as.

This works, however:
```python3
import asyncio

await asyncio.to_thread(
  sheet.ws.update,
  LOCATION,
  FORMULA,
  raw=False
)
```
Cell `A2` will be updated correctly with the formula `=SUM(A1:C1)`, and not just raw text.

**Comment by dgilman** [comment]
Thanks for the catch. I think this is because I have the wrong default kwarg for `value_input_option`. WIll investigate and see what's up.

**Comment by dgilman** [comment]
If you need an immediate workaround (and my hunch is correct) setting `value_input_option="USER_ENTERED"` will get you out of the pickle.
