### ISSUE TITLE
AsyncioGspreadWorksheet.range() stopped accepting numeric boundaries

### ISSUE THREAD

**Issue by user318** [dgilman/gspread_asyncio#45]
Hi,

With this commit: 75bdaee84b227853ca1be031bca51a8561403c80 the definition of function range() in AsyncioGspreadWorksheet class changed from:
```
async def range(self, *args, **kwargs)
```
to:
```
async def range(self, name: str)
```
But wrapped library seems to still support different notations for this function: https://docs.gspread.org/en/latest/api/models/worksheet.html#gspread.worksheet.Worksheet.range. So code that used numeric boundaries now gets an error after updating to a newer version of gsread_asyncio:
```
AsyncioGspreadWorksheet.range() takes 2 positional arguments but 5 were given
```

**Comment by dgilman** [comment]
My apologies - I know there were some methods that documented the extra kwargs but my code never supported passing them through. I ripped them out thinking it was not an API break. Looks like there was one method that did support the kwargs.

I will get a release out to revert this but not right away. In the meantime, if you need a break fix, please take a look at the gspread.utils.rowcol_to_a1 to get it into the string form.

**Comment by user318** [comment]
Thanks. It is not urgent for me. I've already fixed the code that was broken after the update.
