### ISSUE TITLE
spreadsheets.get

### ISSUE THREAD

**Issue by Mat0mba24** [dgilman/gspread_asyncio#49]
In the Google Sheets for Developers documentation, there is a "spreadsheets.get", which has the "includeGridData" parameter, I need this method to get the cell color, is there such a thing in gspread_asyncio or is it planned to add such a method?

**Comment by dgilman** [comment]
This library is a wrapper around the upstream gspread, you need to petition them to add this functionality first.

**Comment by Mat0mba24** [comment]
@dgilman
This functionality is available in gspread, but it is used inside the class there:
https://user-images.githubusercontent.com/76114115/224279779-2f30ddc3-a588-4483-9d59-4ace76ad0e77.png

But there is also fetch_sheet_metadata, most likely we need it.
https://user-images.githubusercontent.com/76114115/224280944-30498bad-e864-4cc1-8cc1-240a33cb1c35.png

**Comment by Mat0mba24** [comment]
> This library is a wrapper around the upstream gspread, you need to petition them to add this functionality first.

@dgilman
This functionality is available in gspread, but it is used inside the class there:
https://user-images.githubusercontent.com/76114115/224279779-2f30ddc3-a588-4483-9d59-4ace76ad0e77.png

But there is also fetch_sheet_metadata, most likely we need it.
https://user-images.githubusercontent.com/76114115/224280944-30498bad-e864-4cc1-8cc1-240a33cb1c35.png
