### ISSUE TITLE
updateDimensionProperties error: string indices must be integers

### ISSUE THREAD

**Issue by gresaggr** [dgilman/gspread_asyncio#64]
Hello.
Trying to set width of columns:
`   body = {
                "requests": [
                    {
                        "updateDimensionProperties": {
                            "dimensions": {
                                "sheetId": sheet_id,
                                "dimension": "COLUMNS",
                                "startIndex": 0,
                                "endIndex": 1
                            },
                            "properties": {
                                "pixelSize": 200
                            },
                        }
                    }
                ]
            }
      await sheet.batch_update(body)
`

and get TypeError: "_string indices must be integers_"

p.s. same with 
`body = {
    "requests": [
        {
            "updateDimensionProperties": {
                "range": {
                    "sheetId": sheet_id,
                    "dimension": "COLUMNS",
                    "startIndex": 0,
                    "endIndex": 1
                },
                "properties": {
                    "pixelSize": 100
                },
                "fields": "pixelSize"
            }
        }
    ]
}`

**Comment by dgilman** [comment]
This is almost certainly an issue with your use of the method / the contents of your update object. We are simply passing the object on to the underlying `batch_update` method in gspread. If you have evidence to the contrary you'll need to give more examples such as a stack trace, working example code etc.

**Comment by gresaggr** [comment]
`try:            
	agcm = gspread_asyncio.AsyncioGspreadClientManager(self._get_creds)
	client = await agcm.authorize()
	a_sheet = await client.create(title=self.table_name, folder_id=FOLDER_ID)
	sheet_id = a_sheet.id
	sheet = await a_sheet.get_worksheet(0)            
	
	body = {
		"requests": [
			{
				"updateDimensionProperties": {
					"dimensions": {
						"sheetId": sheet_id,
						"dimension": "COLUMNS",
						"startIndex": 0,
						"endIndex": 1
					},
					"properties": {
						"pixelSize": 200
					},
				}
			}
		]
	}
	await sheet.batch_update(body)  
	sheet_url = f'https://docs.google.com/spreadsheets/d/{sheet_id}'
	return sheet_url
except Exception as e:
	log.error(f'Error : {e}')
	return None`
