### ISSUE TITLE
`AsyncioGspreadWorksheet.duplicate` returns `gspread.Worksheet` instead of `AsyncioGspreadWorksheet`

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [dgilman/gspread_asyncio#65]
Heya, issue is exactly as said and can be reproduced easily, here is a minimal example:
```python
agc = await agcm.authorize()
spreadsheet = await agc.open_by_url("URL GOES HERE")
worksheet = await spreadsheet.get_worksheet(0)
dup = await worksheet.duplicate(0)
print(type(dup))
```

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
I am using gspread-asyncio 1.8.1 from pip

**Comment by dgilman** [comment]
I'm pushing a fix in the latest release. Unfortunately I shouldn't have implemented this at all as it breaks some assumptions. If you use this function you'll break the caching in AsyncioGspreadSpreadsheet so I don't recommend its use. If you can use `duplicate_sheet()` on the spreadsheet instead that is preferred.
